### ISSUE TITLE
 Time Distorter Freezes if you close the ms dos prompt

### ISSUE THREAD

**Issue by vimaexd** [HistacomUnity/Histacom2-old#6]
### Part

The Time Distorter in Windows 95

### Expected behavior

Animation/Transition to Windows 98

### Actual behavior

Time Distorter Freezes and does nothing

### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/34780309/55682778-c9790f80-592f-11e9-8dd7-e54b0e3c9601.png)

### Steps to reproduce:

1. Install the Time Distorter and press "Go to destination year"
2. When the MS DOS telnet window comes up, close it

### Histacom version

Version 2.0.3-dev

### .NET Framework version (if applicable)

 ?? *edit - I checked, 4.7.2

**Comment by ByteOfMelon** [comment]
Yeah, I've been having a lot of issues with the Time Distorter on Windows 95. I'm gonna check it out and see what's going on. Thanks for the bug report!
