### ISSUE TITLE
I cant find the Installer, I WANT TO PLAY IT, please, how do I run histacom?

### ISSUE THREAD

**Issue by serreyfhfujh** [HistacomUnity/Histacom2-old#8]
### Part

Which part broke or is not behaving properly? (ex. Start Menu, Windows 98)

### Expected behavior

Write here what you're expecting ...

### Actual behavior

Write here what happens instead ...

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1.
2.
3.

**Comment by ByteOfMelon** [comment]
Please do not open issues for things like this. Join our Discord instead, linked in the README.

Also, to play Histacom 2, you'll need to download the latest build over on AppVeyor: https://ci.appveyor.com/project/TheRandomMelon/histacom2. Click "Artifacts", then click "Histacom2.zip" in order to download.

**Comment by serreyfhfujh** [comment]
How do I play it if it is a ZIP file, not an EXE?


Sent from Mail for Windows 10

**Comment by ByteOfMelon** [comment]
I'm sorry, but if you don't know how a zip file works, then you do not have enough computer knowledge to properly play Histacom.

Again, please don't make issues on GitHub for these types of problems. This Issues tab is for development or game bug reporting. Please [read the README](https://github.com/TheRandomMelon/Histacom2/tree/master/README.md) for more information.

**Comment by logantgt** [comment]
We're happy to help out on the Discord server (which you can find an invite link to in the README file in this repository) but I find making a GitHub issue for this is quite inappropriate. If you're having trouble with basic file management, Histacom may not be a very fun game for you to play.
