### ISSUE TITLE
Crash when time traveling to Windows XP

### ISSUE THREAD

**Issue by Alif1211** [HistacomUnity/Histacom2-old#9]
### Part

Time Distorter 0.2

### Expected behavior

It doesn't traveling to Windows XP because a bug

### Steps to reproduce:

When in Windows 98
1.Go to Internet Explorer
2.Click www.12padams.com link
3.Download Web Chat 1999
4.Install Web Chat 1999
5.Open Web Chat 1999
6.Type my username to Web Chat 1999
7.Wait the chat until the tdistortv2.exe available
8.Download tdistortv2.exe
9.Install Time Distorter 0.2
10.Open Time Distorter 0.2
11.Click the Button to Travel to 2002
12.Screen Flashing
13.Green big Number showing from 1900 to 2000 then 2002
14.Histacom2.Engine preparing Windows XP
15.It disappear

### Histacom version
Histacom 2.0.3-dev-14

### .NET Framework version (if applicable)
.NET Framework 4.7.1

**Comment by logantgt** [comment]
Thank you for reporting this bug, but I can't find the version of Histacom that you were playing that you encountered this error in. Please give a Commit ID for the build you're playing or give us a download link so we can look into this further. Thank you!

**Comment by Alif1211** [comment]
The Commit ID is "13a79337"
